config/routes.rb
Rails.application.routes.draw do
  root 'products#index'

  # portfolio
  resources :products, only: [:index]
  resource  :profile,  only: [:show]
  resource  :contact,  only: [:show]

  get "btng" => "btng#btn_generator"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/btng_controller.rb
class BtngController < ApplicationController
  def btn_generator
    @page_title = "BTNG - CSSボタンジェネレーター"
    @header_name = "BTNG"

    @csses = [
      #{name: , name_id: , min: , max: , step: , value: , span_id: , span_value: }
      {name: "height:", name_id: "height", min: "0", max: "120", step: "1", value: "20", span_id: "height-value", span_value: "20px"},
      {name: "width:", name_id: "width", min: "0", max: "240", step: "1", value: "40", span_id: "width-value", span_value: "40px"},
      {name: "border-radius:", name_id: "radius", min: "0", max: "60", step: "1", value: "2", span_id: "radius-value", span_value: "2px"},
      {name: "border-width:", name_id: "border-width", min: "0", max: "20", step: "1", value: "1", span_id: "border-width-value", span_value: "1px"},
      {name: "border-style:", name_id: "border-style", min: "0", max: "9", step: "1", value: "2", span_id: "border-style-value", span_value: "solid"},
      {name: "border-color:", name_id: "border-color", min: "0", max: "16777215", step: "1", value: "12237498", span_id: "border-color-value", span_value: "#BABABA"},
      {name: "font-size:", name_id: "font-size", min: "0", max: "100", step: "1", value: "11", span_id: "font-size-value", span_value: "11px"},
      {name: "font-weight:", name_id: "font-weight", min: "100", max: "900", step: "100", value: "400", span_id: "font-weight-value", span_value: "400"},
      {name: "color:", name_id: "color", min: "0", max: "16777215", step: "1", value: "0", span_id: "color-value", span_value: "#000000"},
      {name: "background-color:", name_id: "background-color", min: "0", max: "16777215", step: "1", value: "16777215", span_id: "background-color-value", span_value: "#FFFFFF"},
      {name: "box-shadow-x:", name_id: "box-shadow-x", min: "-30", max: "30", step: "1", value: "0", span_id: "box-shadow-x-value", span_value: "0px"},
      {name: "box-shadow-y:", name_id: "box-shadow-y", min: "-30", max: "30", step: "1", value: "0", span_id: "box-shadow-y-value", span_value: "0px"},
      {name: "box-shadow-blur:", name_id: "box-shadow-blur", min: "0", max: "100", step: "1", value: "0", span_id: "box-shadow-blur-value", span_value: "0px"},
      {name: "box-shadow-spread:", name_id: "box-shadow-spread", min: "-100", max: "100", step: "1", value: "0", span_id: "box-shadow-spread-value", span_value: "0px"},
      {name: "box-shadow-color:", name_id: "box-shadow-color", min: "0", max: "16777215", step: "1", value: "0", span_id: "box-shadow-color-value", span_value: "#000000"},
      {name: "box-shadow-opacity:", name_id: "box-shadow-opacity", min: "0", max: "1", step: "0.01", value: "0.75", span_id: "box-shadow-opacity-value", span_value: "0.75"}
    ]
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @products = [
      #{name: , id_name: , img_url: , date:}
      {name: "BTNG", id_name: "btng-product", img_url: "/products-img/btng-img3.png", date: "July 06, 2019"},
      {name: "Portfolio", id_name: "portfolio", img_url: "/products-img/portfolio-img.png", date: "Mar. 24, 2019"},
      {name: "mkidea", id_name: "mkidea", img_url: "/products-img/mkidea-img.png", date: "Oct. 31, 2018"},
      {name: "BookList", id_name: "booklist", img_url: "/products-img/BookList-img.png", date: "Oct. 04, 2018"},
      {name: "LINE STAMP", id_name: "linestamp", img_url: "/products-img/linestamp-img.png", date: "Dec. 19, 2016 ~ "}
    ]

    @hide_products = [
      #{name: , img_url: , date: , url: , hide_id: , close_id: , framework: , comment: }
      {name: "BTNG", img_url: "/products-img/btng-img3.png", date: "July 06, 2019", url: "http://okaryo-tr.com/btng", hide_id: "hide-btng", close_id:"close-btng" , framework: "", comment: "Button Generator, \"BTNG\" for short. You can try making a button at will!"},
      {name: "Portfolio", img_url: "/products-img/portfolio-img.png", date: "Mar. 24, 2019", url: "", hide_id: "hide-portfolio", close_id: "close-portfolio", framework: "framework: Rails", comment: "My portfolio site that you are looking at now! You can find out my profile. Feel free contact me if you are interested in me!"},
      {name: "mkidea", img_url: "/products-img/mkidea-img.png", date: "Oct. 31, 2018", url: "https://mkidea.jp", hide_id: "hide-mkidea", close_id: "close-mkidea", framework: "framework: Rails", comment: "My second product! You can make many ideas with this app! I'm going to make this site a platform to make ideas."},
      {name: "BookList", img_url: "/products-img/BookList-img.png", date: "Oct. 04, 2018", url: "https://book-list.jp", hide_id: "hide-booklist", close_id: "close-booklist", framework: "framework: Rails", comment: "My first product! You can share several books in the form of List on your Twitter."},
      {name: "LINE STAMP", img_url: "/products-img/linestamp-img.png", date: "Dec. 19, 2016 ~ ", url: "https://store.line.me/stickershop/author/119727", hide_id: "hide-linestamp", close_id: "close-linestamp", framework: "", comment: "My original characters! You can buy them at LINE STORE!"}
    ]
  end
  
  def contact
  end
  
  def about
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = [
      #{name: , id_name: , img_url: , date:}
      {name: "BTNG", id_name: "btng-product", img_url: "/products-img/btng-img3.png", date: "July 06, 2019"},
      {name: "Portfolio", id_name: "portfolio", img_url: "/products-img/portfolio-img.png", date: "Mar. 24, 2019"},
      {name: "mkidea", id_name: "mkidea", img_url: "/products-img/mkidea-img.png", date: "Oct. 31, 2018"},
      {name: "BookList", id_name: "booklist", img_url: "/products-img/BookList-img.png", date: "Oct. 04, 2018"},
      {name: "LINE STAMP", id_name: "linestamp", img_url: "/products-img/linestamp-img.png", date: "Dec. 19, 2016 ~ "}
    ]

    @hide_products = [
      #{name: , img_url: , date: , url: , hide_id: , close_id: , framework: , comment: }
      {name: "BTNG", img_url: "/products-img/btng-img3.png", date: "July 06, 2019", url: "http://okaryo-tr.com/btng", hide_id: "hide-btng", close_id:"close-btng" , framework: "", comment: "Button Generator, \"BTNG\" for short. You can try making a button at will!"},
      {name: "Portfolio", img_url: "/products-img/portfolio-img.png", date: "Mar. 24, 2019", url: "", hide_id: "hide-portfolio", close_id: "close-portfolio", framework: "framework: Rails", comment: "My portfolio site that you are looking at now! You can find out my profile. Feel free contact me if you are interested in me!"},
      {name: "mkidea", img_url: "/products-img/mkidea-img.png", date: "Oct. 31, 2018", url: "https://mkidea.jp", hide_id: "hide-mkidea", close_id: "close-mkidea", framework: "framework: Rails", comment: "My second product! You can make many ideas with this app! I'm going to make this site a platform to make ideas."},
      {name: "BookList", img_url: "/products-img/BookList-img.png", date: "Oct. 04, 2018", url: "https://book-list.jp", hide_id: "hide-booklist", close_id: "close-booklist", framework: "framework: Rails", comment: "My first product! You can share several books in the form of List on your Twitter."},
      {name: "LINE STAMP", img_url: "/products-img/linestamp-img.png", date: "Dec. 19, 2016 ~ ", url: "https://store.line.me/stickershop/author/119727", hide_id: "hide-linestamp", close_id: "close-linestamp", framework: "", comment: "My original characters! You can buy them at LINE STORE!"}
    ]
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
  end
end

app/helpers/aboutme_helper.rb
module AboutmeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title
    title = "OKARYO"
    title = @page_title if @page_title
    return title
  end

  def header_name
    name = "OKARYO"
    name = @header_name if @header_name
    return name
  end
end

app/helpers/btng_helper.rb
module BtngHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/show.html.erb
<div class="tabs">
  <div class="tab_item tab_products3"><%= link_to("PRODUCTS", products_path) %></div>

  <div class="tab_item tab_about3"><%= link_to("ABOUT ME", profile_path) %></div>

  <div class="tab_item tab_contact3"><%= link_to("CONTACT", "#") %></div>
</div>

<div class="main wrapper">
  <div class="container">
    <div class="note">
      <p>Feel free to contact me!</p>
    </div>
  
    <div class="form contact-form">
      <div class="form-body">
        
        <!%= form_tag("/login") do %>
          <p>E-mail</p>
          <input name="email" value="未実装のためご用の方はTwitterまでどうぞ">
          <p>Subject</p>
          <input name="subject" value="未実装のためご用の方はTwitterまでどうぞ">
          <p>Message</p>
          <textarea name="body" rows="8">not implemented, so please go to Twitter</textarea>
          <input type="submit" value="Not Send">
        <!% end %>
      </div>
    </div>
  </div>
  
</div>

app/views/home/about.html.erb
<div class="tabs">
  <div class="tab_item tab_products2"><%= link_to("PRODUCTS", "/") %></div>

  <div class="tab_item tab_about2"><%= link_to("ABOUT ME", "/about") %></div>

  <div class="tab_item tab_contact2"><%= link_to("CONTACT", "/contact") %></div>
</div>

<div class="main wrapper">
  <div class="container">
    <ul>
      <div class="list-unit">
        <li>I am</li>
        <div class="photo-and-name">
          <div class="photo">
            <img src="/oba.png">
          </div>
          <div class="name">
            <p>Offline Name: Ryotaro Oka</p>
            <p>Online Name: okaryo / オカリヨ</p>
          </div>
        </div>
      </div>
      <div class="list-unit">
        <li>Experience</li>
        <div class="about-unit">
          <p class="about-main">Web engineer (Aug. 2019 - present)</p>
          <p class="about-sub">internship</p>
        </div>
        <div class="about-unit">
          <p class="about-main">cram school teacher (May 2018 - Mar. 2019)</p>
          <p class="about-sub">part time job</p>
        </div>
        <div class="about-unit">
          <p class="about-main">baker (May 2015 - Feb. 2017)</p>
          <p class="about-sub">part time job</p>
        </div>
      </div>
      

      <div class="list-unit">
        <li>Education</li>
        <div class="about-unit">
          <p class="about-main">The University of Tokyo, Faculty of Law (Apr. 2018 - present)</p>
          <p class="about-sub">DepartmentⅠ: General Legal Studies Course</p>
        </div>
        <div class="about-unit">
          <p class="about-main">Taking a year off from university (Apr. 2017 - Mar. 2018)</p>
          <p class="about-sub">Lost the meaning of life</p>
        </div>
        <div class="about-unit">
          <p class="about-main">The University of Tokyo, Faculty of Arts and Sciences (Apr. 2015 - Mar. 2017)</p>
          <p class="about-sub">Human Sciences Ⅰ</p>
        </div>
        <div class="about-unit">
          <p class="about-main">SUNDAI Ochanomizu3 LB→LA (Apr. 2014 - Mar. 2015)</p>
          <p class="about-sub">Ronin</p>
        </div>
      </div>
      
      <div class="list-unit">
        <li>Online Activity</li>
        <div class="link-set"><a class="fas fa-external-link-square-alt" href="https://twitter.com/okaryo_tr"  target="_blank"></a><a class="about-link" href="https://twitter.com/okaryo_tr" target="_blank">Twitter</a></div>
        <div class="link-set"><a class="fas fa-external-link-square-alt" href="https://bookmeter.com/users/739784" target="_blank"></a><a class="about-link" href="https://bookmeter.com/users/739784" target="_blank">Bookmeter</a></div>
        <div class="link-set"><a class="fas fa-external-link-square-alt" href="http://www.jognote.com/users/436622" target="_blank"></a><a class="about-link" href="http://www.jognote.com/users/436622" target="_blank">Jognote</a></div>
        <div class="link-set"><a class="fas fa-external-link-square-alt" href="https://store.line.me/stickershop/author/119727" target="_blank"></a><a class="about-link" href="https://store.line.me/stickershop/author/119727" target="_blank">LINE STAMP</a></div>
        <div class="link-set"><a class="fas fa-external-link-square-alt" href="https://okaryo.hatenablog.com/" target="_blank"></a><a class="about-link" href="https://okaryo.hatenablog.com/" target="_blank">Blog</a></div>
        <div class="link-set"><a class="fas fa-external-link-square-alt" href="https://anchor.fm/booking-talk" target="_blank"></a><a class="about-link" href="https://anchor.fm/booking-talk" target="_blank">Podcast</a></div>
        <div class="link-set"><a class="fas fa-external-link-square-alt" href="https://github.com/okaryo" target="_blank"></a><a class="about-link" href="https://github.com/okaryo" target="_blank">GitHub</a></div>
        <div class="link-set"><a class="fas fa-external-link-square-alt" href="https://qiita.com/okaryo" target="_blank"></a><a class="about-link" href="https://qiita.com/okaryo" target="_blank">Qiita</a></div>
        <div class="link-set"><a class="fas fa-external-link-square-alt" href="https://atcoder.jp/users/okaryo" target="_blank"></a><a class="about-link" href="https://atcoder.jp/users/okaryo" target="_blank">AtCoder</a></div>
        <div class="link-set"><a class="fas fa-external-link-square-alt" href="https://www.amazon.jp/hz/wishlist/ls/3F7T4Z1GG7ORH?ref_=wl_share"  target="_blank"></a><a class="about-link" href="https://www.amazon.jp/hz/wishlist/ls/3F7T4Z1GG7ORH?ref_=wl_share" target="_blank">Wish List</a></div>
      </div>
    </ul>
  </div>
</div>

app/views/home/contact.html.erb
<div class="tabs">
  <div class="tab_item tab_products3"><%= link_to("PRODUCTS", "/") %></div>

  <div class="tab_item tab_about3"><%= link_to("ABOUT ME", "/about") %></div>

  <div class="tab_item tab_contact3"><%= link_to("CONTACT", "/contact") %></div>
</div>

<div class="main wrapper">
  <div class="container">
    <div class="note">
      <p>Feel free to contact me!</p>
    </div>
  
    <div class="form contact-form">
      <div class="form-body">
        
        <!%= form_tag("/login") do %>
          <p>E-mail</p>
          <input name="email" value="未実装のためご用の方はTwitterまでどうぞ">
          <p>Subject</p>
          <input name="subject" value="未実装のためご用の方はTwitterまでどうぞ">
          <p>Message</p>
          <textarea name="body" rows="8">not implemented, so please go to Twitter</textarea>
          <input type="submit" value="Not Send">
        <!% end %>
      </div>
    </div>
  </div>
  
</div>

app/views/layouts/_footer.html.erb
<footer class="footer clearfix">
  <div class="footer-menus">
    <div class="footer-menu">
      <div class="footer_items">
        <p class="footer_item_title">Portfolio</p>
        <p class="footer_item">Products</p>
        <p class="footer_item">Profile</p>
        <p class="footer_item">Contact</p>
      </div>
    </div>
    <div class="footer-menu">
      <div class="footer_items">
        <p class="footer_item_title">Products</p>
        <p class="footer_item">BTNG</p>
        <p class="footer_item">mkidea</p>
        <p class="footer_item">BookList</p>
        <p class="footer_item">Original Character</p>
      </div>
    </div>
    <div class="footer-menu">
      <div class="footer_items">
        <p class="footer_item_title">Social</p>
        <p class="footer_item">Twitter</p>
        <p class="footer_item">Bookmeter</p>
        <p class="footer_item">Jognote<p/>
        <p class="footer_item">LINE STAMP<p/>
        <p class="footer_item">Blog<p/>
        <p class="footer_item">Podcast<p/>
        <p class="footer_item">Github<p/>
        <p class="footer_item">Qiita<p/>
        <p class="footer_item">AtCoder<p/>
        <p class="footer_item">Wish List<p/>
      </div>
    </div>
  </div>
  <p class="copyright">Copyright ©︎2019 OKARYO</p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="main-header">
    <div class="header-icon"></div>
    <div class="header-name"><%= link_to(header_name, root_path) %></div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheets" href="home.scss">
    <link rel="stylesheets" href="top.scss">
    <link rel="stylesheets" href="about.scss">
    <link rel="stylesheets" href="contact.scss">
    <link rel="stylesheets" href="btng.scss">
    <link rel="stylesheets" href="responsive.scss">

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <%= favicon_link_tag('/favicon.ico') %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    
    <%= yield %>
    
    <%= render 'layouts/footer' %>
  </body>
  
</html>

app/views/products/index.html.erb
<div class="tabs clearfix">
  <div class="tab_item tab_products1" id="tab_products"><%= link_to("PRODUCTS", "#") %></div>

  <div class="tab_item tab_about1" id="tab_about"><%= link_to("ABOUT ME", profile_path) %></div>

  <div class="tab_item tab_contact1" id="tab_contact"><%= link_to("CONTACT", contact_path) %></div>
</div>

<div id="hide-wrapper"></div>
<div class="products-main products-wrapper clearfix">
  <div class="products-container clearfix">
    <% @products.each do |product| %>
      <div class="product-unit">
        <div class="product" id="<%= product[:id_name] %>">
          <div class="product-img">
            <img src="<%= product[:img_url] %>">
          </div>
          <div class="product-text">
            <p class="product-title"><%= product[:name] %></p>
            <p class="product-day"><%= product[:date] %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<% @hide_products.each do |hide_product| %>
  <div class="hide-unit" id="<%= hide_product[:hide_id] %>">
    <div class="hibe-img">
      <img src="<%= hide_product[:img_url] %>">
    </div>
    <div class="hide-explain">
      <div class="close" id="<%= hide_product[:close_id] %>">
        <i class="fas fa-times"></i>
      </div>
      <p class="product-title hide-title"><%= hide_product[:name] %></p>
      <p class="product-day hide-day"><%= hide_product[:date] %></p>
      <p class="flame-work"><%= hide_product[:framework] %></p>
      <p class="comment"><%= hide_product[:comment] %></p>
      <% if hide_product[:url] != "" %>
        <a href="<%= hide_product[:url] %>" target="_blank" class="visit-website">▷ Visit WebSite</a>
      <% else %>
        <a class="visit-website">▷ You are already here!</a>
      <% end %>
    </div>
  </div>
<% end %>

<script type="text/javascript">
  $('#btng-product').click(function() {
    $('#hide-btng').css('display', 'block');
    $('#hide-btng').css('z-index', '20');
    $('#hide-wrapper').css('display', 'block');
  });
  $('#portfolio').click(function() {
    $('#hide-portfolio').css('display', 'block');
    $('#hide-portfolio').css('z-index', '20');
    $('#hide-wrapper').css('display', 'block');
  });
  $('#mkidea').click(function() {
    $('#hide-mkidea').css('display', 'block');
    $('#hide-mkidea').css('z-index', '20');
    $('#hide-wrapper').css('display', 'block');
  });
  $('#booklist').click(function() {
    $('#hide-booklist').css('display', 'block');
    $('#hide-booklist').css('z-index', '20');
    $('#hide-wrapper').css('display', 'block');
  });
  $('#linestamp').click(function() {
    $('#hide-linestamp').css('display', 'block');
    $('#hide-linestamp').css('z-index', '20');
    $('#hide-wrapper').css('display', 'block');
  });

  $('#hide-wrapper').click(function() {
    $('#hide-btng').css('display', 'none');
    $('#hide-portfolio').css('display', 'none');
    $('#hide-mkidea').css('display', 'none');
    $('#hide-booklist').css('display', 'none');
    $('#hide-linestamp').css('display', 'none');
    $('#hide-wrapper').css('display', 'none');
  });
  $('#close-btng').click(function() {
    $('#hide-btng').css('display', 'none');
    $('#hide-wrapper').css('display', 'none');
  });
  $('#close-portfolio').click(function() {
    $('#hide-portfolio').css('display', 'none');
    $('#hide-wrapper').css('display', 'none');
  });
  $('#close-mkidea').click(function() {
    $('#hide-mkidea').css('display', 'none');
    $('#hide-wrapper').css('display', 'none');
  });
  $('#close-booklist').click(function() {
    $('#hide-booklist').css('display', 'none');
    $('#hide-wrapper').css('display', 'none');
  });
  $('#close-linestamp').click(function() {
    $('#hide-linestamp').css('display', 'none');
    $('#hide-wrapper').css('display', 'none');
  });
</script>

app/views/profiles/show.html.erb
<div class="tabs">
  <div class="tab_item tab_products2"><%= link_to("PRODUCTS", products_path) %></div>

  <div class="tab_item tab_about2"><%= link_to("ABOUT ME", "#") %></div>

  <div class="tab_item tab_contact2"><%= link_to("CONTACT", contact_path) %></div>
</div>

<div class="main wrapper">
  <div class="container">
    <ul>
      <div class="list-unit">
        <li>I am</li>
        <div class="photo-and-name">
          <div class="photo">
            <img src="/oba.png">
          </div>
          <div class="name">
            <p>Offline Name: Ryotaro Oka</p>
            <p>Online Name: okaryo / オカリヨ</p>
          </div>
        </div>
      </div>
      <div class="list-unit">
        <li>Experience</li>
        <div class="about-unit">
          <p class="about-main">Web engineer (Aug. 2019 - present)</p>
          <p class="about-sub">internship</p>
        </div>
        <div class="about-unit">
          <p class="about-main">cram school teacher (May 2018 - Mar. 2019)</p>
          <p class="about-sub">part time job</p>
        </div>
        <div class="about-unit">
          <p class="about-main">baker (May 2015 - Feb. 2017)</p>
          <p class="about-sub">part time job</p>
        </div>
      </div>
      

      <div class="list-unit">
        <li>Education</li>
        <div class="about-unit">
          <p class="about-main">The University of Tokyo, Faculty of Law (Apr. 2018 - present)</p>
          <p class="about-sub">DepartmentⅠ: General Legal Studies Course</p>
        </div>
        <div class="about-unit">
          <p class="about-main">Taking a year off from university (Apr. 2017 - Mar. 2018)</p>
          <p class="about-sub">Lost the meaning of life</p>
        </div>
        <div class="about-unit">
          <p class="about-main">The University of Tokyo, Faculty of Arts and Sciences (Apr. 2015 - Mar. 2017)</p>
          <p class="about-sub">Human Sciences Ⅰ</p>
        </div>
        <div class="about-unit">
          <p class="about-main">SUNDAI Ochanomizu3 LB→LA (Apr. 2014 - Mar. 2015)</p>
          <p class="about-sub">Ronin</p>
        </div>
      </div>
      
      <div class="list-unit">
        <li>Online Activity</li>
        <div class="link-set"><a class="fas fa-external-link-square-alt" href="https://twitter.com/okaryo_tr"  target="_blank"></a><a class="about-link" href="https://twitter.com/okaryo_tr" target="_blank">Twitter</a></div>
        <div class="link-set"><a class="fas fa-external-link-square-alt" href="https://bookmeter.com/users/739784" target="_blank"></a><a class="about-link" href="https://bookmeter.com/users/739784" target="_blank">Bookmeter</a></div>
        <div class="link-set"><a class="fas fa-external-link-square-alt" href="http://www.jognote.com/users/436622" target="_blank"></a><a class="about-link" href="http://www.jognote.com/users/436622" target="_blank">Jognote</a></div>
        <div class="link-set"><a class="fas fa-external-link-square-alt" href="https://store.line.me/stickershop/author/119727" target="_blank"></a><a class="about-link" href="https://store.line.me/stickershop/author/119727" target="_blank">LINE STAMP</a></div>
        <div class="link-set"><a class="fas fa-external-link-square-alt" href="https://okaryo.hatenablog.com/" target="_blank"></a><a class="about-link" href="https://okaryo.hatenablog.com/" target="_blank">Blog</a></div>
        <div class="link-set"><a class="fas fa-external-link-square-alt" href="https://anchor.fm/booking-talk" target="_blank"></a><a class="about-link" href="https://anchor.fm/booking-talk" target="_blank">Podcast</a></div>
        <div class="link-set"><a class="fas fa-external-link-square-alt" href="https://github.com/okaryo" target="_blank"></a><a class="about-link" href="https://github.com/okaryo" target="_blank">GitHub</a></div>
        <div class="link-set"><a class="fas fa-external-link-square-alt" href="https://qiita.com/okaryo" target="_blank"></a><a class="about-link" href="https://qiita.com/okaryo" target="_blank">Qiita</a></div>
        <div class="link-set"><a class="fas fa-external-link-square-alt" href="https://atcoder.jp/users/okaryo" target="_blank"></a><a class="about-link" href="https://atcoder.jp/users/okaryo" target="_blank">AtCoder</a></div>
        <div class="link-set"><a class="fas fa-external-link-square-alt" href="https://www.amazon.jp/hz/wishlist/ls/3F7T4Z1GG7ORH?ref_=wl_share"  target="_blank"></a><a class="about-link" href="https://www.amazon.jp/hz/wishlist/ls/3F7T4Z1GG7ORH?ref_=wl_share" target="_blank">Wish List</a></div>
      </div>
    </ul>
  </div>
</div>